/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas;

/**
 *
 * @author Victor
 */
import Modelo.Asiento;
import Modelo.Proyeccion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;

public class DialogSeleccionAsientos extends javax.swing.JDialog {
    private PanelElegirAsientos panelAsientos;

    // --- CONSTRUCTOR CORREGIDO ---
  public DialogSeleccionAsientos(JFrame parent, List<Asiento> asientosBD, List<Asiento> asientosParaAnular, Proyeccion proyeccion) {
    
    super(parent, "Selección de Asientos - " + proyeccion.getTitulo(), true);
    
    // 1. LLAMAMOS a initComponents()
    initComponents(); 

    try {
        panelAsientos = new PanelElegirAsientos();
        panelAsientos.cargarAsientos(asientosBD, asientosParaAnular);
        
        // 2. CONFIGURACIÓN DEL CONTENEDOR FINAL:
        this.getContentPane().setLayout(new BorderLayout()); 
        this.getContentPane().add(panelAsientos, BorderLayout.CENTER); // Añadimos el contenido
        
        // 3. Configuramos la ventana y forzamos el tamaño MÍNIMO
        this.setPreferredSize(new Dimension(500, 450)); 
        this.pack(); 
        this.setMinimumSize(new Dimension(500, 450)); // FUERZA el JDialog a mantener el tamaño
        this.setLocationRelativeTo(parent); 
        
    } catch (Exception ex) {
        // En caso de error, muestra el mensaje y deja el diálogo vacío.
        javax.swing.JOptionPane.showMessageDialog(this, "ERROR AL CARGAR ASIENTOS (Ver consola): " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
    // --- MÉTODOS DE UTILIDAD ---
    
    public void setObservador(java.util.function.Consumer<List<Asiento>> observador) {
        panelAsientos.setObservador(observador);
    }
    
    public List<Asiento> getAsientosSeleccionados() {
        return panelAsientos.getAsientosSeleccionados();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
