
package Vistas;

/**
 *
 * @author Victor
 */
import Modelo.Asiento;
import Modelo.EstadoAsiento;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import java.util.function.Consumer;

public class PanelSalas extends javax.swing.JPanel {
    
    private List<Asiento> asientosSeleccionados;
    private Consumer<List<Asiento>> observador;
    
    
    private final Color COLOR_LIBRE = new Color(144, 238, 144); // Verde
    private final Color COLOR_OCUPADO = new Color(255, 99, 71); // Rojo
    private final Color COLOR_SELECCIONADO = new Color(100, 149, 237); // Azul

    /**
     * Creates new form PanelSalas
     */
    public PanelSalas() {
        initComponents();
        this.asientosSeleccionados = new ArrayList<>();
    }
    public void setObservador(Consumer<List<Asiento>> observador) {
        this.observador = observador;
    }
  
    public void cargarAsientos(List<Asiento> listaAsientos) {
        this.removeAll(); 
        this.asientosSeleccionados.clear(); 

        if (listaAsientos == null || listaAsientos.isEmpty()) {
            this.revalidate();
            this.repaint();
            return;
        }

        int maxColumna = 0;
        for (Asiento a : listaAsientos) {
            if (a.getNumero() > maxColumna) maxColumna = a.getNumero();
        }
        int filas = (int) Math.ceil((double) listaAsientos.size() / maxColumna);

        this.setLayout(new GridLayout(filas, maxColumna, 5, 5));

        for (Asiento asiento : listaAsientos) {
            JButton btn = new JButton(asiento.getFila() + "-" + asiento.getNumero());
            
            if (asiento.getEstado() == EstadoAsiento.OCUPADO) {
                btn.setBackground(COLOR_OCUPADO);
                btn.setEnabled(false); // No se puede clicar
            } else {
                btn.setBackground(COLOR_LIBRE);
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        gestionarSeleccion(btn, asiento);
                    }
                });
            }
            this.add(btn);
        }

        this.revalidate();
        this.repaint();
    }

    private void gestionarSeleccion(JButton btn, Asiento asiento) {
        if (asientosSeleccionados.contains(asiento)) {
            asientosSeleccionados.remove(asiento);
            btn.setBackground(COLOR_LIBRE);
        } else {
            asientosSeleccionados.add(asiento);
            btn.setBackground(COLOR_SELECCIONADO);
        }

        if (observador != null) {
            observador.accept(asientosSeleccionados);
        }
    }

    public List<Asiento> getAsientosSeleccionados() {
        return asientosSeleccionados;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
