package Vistas;

/**
 *
 * @author Victor
 */
import Modelo.Asiento;
import Modelo.EstadoAsiento;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import java.util.function.Consumer;

public class PanelElegirAsientos extends javax.swing.JPanel {

    private List<Asiento> asientosSeleccionados;
    private Consumer<List<Asiento>> observador;
    private List<Asiento> asientosTicketActual;

    private final Color COLOR_LIBRE = new Color(144, 238, 144); // Verde (Seleccionable)
    private final Color COLOR_OCUPADO = new Color(255, 99, 71); // Rojo (No seleccionable)
    private final Color COLOR_SELECCIONADO = new Color(100, 149, 237); // Azul (Seleccionado por el usuario)

    /**
     * Creates new form PanelSalas
     */
    public PanelElegirAsientos() {
        initComponents();
        this.asientosSeleccionados = new ArrayList<>();
    }

    public void setObservador(Consumer<List<Asiento>> observador) {
        this.observador = observador;
    }

    public void cargarAsientos(List<Asiento> listaAsientos, List<Asiento> asientosParaAnular) {
        this.removeAll();
        this.asientosSeleccionados.clear();

        // Guardamos la lista de asientos del ticket actual para usarla en la lógica
        this.asientosTicketActual = (asientosParaAnular != null) ? asientosParaAnular : new ArrayList<>();

        if (listaAsientos == null || listaAsientos.isEmpty()) {
            this.revalidate();
            this.repaint();
            return;
        }

        // ... (El código de cálculo de GridLayout sigue igual) ...
        for (Asiento asiento : listaAsientos) {
            JButton btn = new JButton(asiento.getFila() + "-" + asiento.getNumero());

            // --- LÓGICA DE ESTADOS REVISADA PARA ANULACIÓN ---
            if (asientosTicketActual.contains(asiento)) {
                // Caso 1: Pertenece al ticket que estoy gestionando (LO PINTO AZUL y lo HABILITO)
                btn.setBackground(COLOR_SELECCIONADO);
                btn.setEnabled(true);

                // También lo marcamos como seleccionado internamente para que aparezca en la JList lateral
                asientosSeleccionados.add(asiento);
            } else if (asiento.getEstado() == EstadoAsiento.LIBRE) {
                // Caso 2: Asiento verdaderamente libre (VERDE)
                btn.setBackground(COLOR_LIBRE);
                btn.setEnabled(true);
            } else {
                // Caso 3: Ocupado por otro ticket (ROJO)
                btn.setBackground(COLOR_OCUPADO);
                btn.setEnabled(false);
            }

            // El ActionListener debe aplicarse a todos los botones habilitados (Casos 1 y 2)
            if (btn.isEnabled()) {
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        gestionarSeleccion(btn, asiento);
                    }
                });
            }

            this.add(btn);
        }
        // ... (revalidate, repaint, etc.) ...

        // Disparar el observador para actualizar la lista lateral y el total al cargar el ticket
        if (observador != null) {
            observador.accept(asientosSeleccionados);
        }
    }

    private void gestionarSeleccion(JButton btn, Asiento asiento) {
        if (asientosSeleccionados.contains(asiento)) {
            // Deseleccionar: Remover de la lista y volver a LIBRE (verde)
            asientosSeleccionados.remove(asiento);
            btn.setBackground(COLOR_LIBRE);
        } else {
            // Seleccionar: Agregar a la lista y pintar de SELECCIONADO (azul)
            asientosSeleccionados.add(asiento);
            btn.setBackground(COLOR_SELECCIONADO);
        }

        // Notificar a la vista principal (PanelGestionTickets) para actualizar la JList y el total.
        if (observador != null) {
            observador.accept(asientosSeleccionados);
        }
    }

    public List<Asiento> getAsientosSeleccionados() {
        return asientosSeleccionados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
