package Vistas;

/**
 *
 * @author Victor
 */
import Modelo.Asiento;
import Modelo.EstadoAsiento;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import java.util.function.Consumer;

public class PanelElegirAsientos extends javax.swing.JPanel {

    private List<Asiento> asientosSeleccionados;
    private Consumer<List<Asiento>> observador;
    private List<Asiento> asientosTicketActual;

    private final Color COLOR_LIBRE = new Color(144, 238, 144); // Verde (Seleccionable)
    private final Color COLOR_OCUPADO = new Color(255, 99, 71); // Rojo (No seleccionable)
    private final Color COLOR_SELECCIONADO = new Color(100, 149, 237); // Azul (Seleccionado por el usuario)

    /**
     * Creates new form PanelSalas
     */
    public PanelElegirAsientos() {
        initComponents();
        this.asientosSeleccionados = new ArrayList<>();
    }

    public void setObservador(Consumer<List<Asiento>> observador) {
        this.observador = observador;
    }

    public void cargarAsientos(List<Asiento> listaAsientos, List<Asiento> asientosParaAnular) { 
    this.removeAll(); 
    this.asientosSeleccionados.clear(); 

    if (listaAsientos == null || listaAsientos.isEmpty()) {
        this.revalidate();
        this.repaint();
        return;
    }

    // --- Lógica Defensiva para determinar el GridLayout (Filas x Columnas) ---
    int maxColumna = 0;
    for (Asiento a : listaAsientos) {
        if (a.getNumero() > maxColumna) maxColumna = a.getNumero();
    }
    
    // Protección contra división por cero: si no hay columnas (maxColumna=0), usamos 1 por seguridad.
    if (maxColumna == 0) maxColumna = 1; 
    
    int filas = (int) Math.ceil((double) listaAsientos.size() / maxColumna);
    
    // Si hay más asientos que el cálculo, forzamos un GridLayout simple.
    if (filas == 0) filas = 1;

    this.setLayout(new GridLayout(filas, maxColumna, 5, 5));

    for (Asiento asiento : listaAsientos) {
        JButton btn = new JButton(asiento.getFila() + "-" + asiento.getNumero());
        
        // --- LÓGICA DE ESTADOS ---
        if (asiento.getEstado() == EstadoAsiento.LIBRE) {
            btn.setBackground(COLOR_LIBRE);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    gestionarSeleccion(btn, asiento);
                }
            });
        } else {
            btn.setBackground(COLOR_OCUPADO);
            btn.setEnabled(false); 
        }
        
        this.add(btn);
    }

    this.revalidate();
    this.repaint();
}

    private void gestionarSeleccion(JButton btn, Asiento asiento) {
        if (asientosSeleccionados.contains(asiento)) {
            // Deseleccionar: Remover de la lista y volver a LIBRE (verde)
            asientosSeleccionados.remove(asiento);
            btn.setBackground(COLOR_LIBRE);
        } else {
            // Seleccionar: Agregar a la lista y pintar de SELECCIONADO (azul)
            asientosSeleccionados.add(asiento);
            btn.setBackground(COLOR_SELECCIONADO);
        }

        // Notificar a la vista principal (PanelGestionTickets) para actualizar la JList y el total.
        if (observador != null) {
            observador.accept(asientosSeleccionados);
        }
    }

    public List<Asiento> getAsientosSeleccionados() {
        return asientosSeleccionados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
