/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author Victor
 */
import Modelo.*;
import Persistencia.*;
import Vistas.PanelElegirAsientos;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PanelGestionTickets extends javax.swing.JPanel {

    /**
     * Creates new form PanelGestionTickets
     */
    private PanelElegirAsientos miPanelSalas;
    private Comprador compradorActual = null;
    private TicketCompra ticketActual = null;

    public PanelGestionTickets() {
        initComponents();
        miPanelSalas = new PanelElegirAsientos();
        cargarDatosIniciales();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnBuscar = new javax.swing.JToggleButton();
        jtfDNI = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        lblGestion = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        cbPelicula = new javax.swing.JComboBox<>();
        lblSala = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox<>();
        btnSeleccionarAsientos = new javax.swing.JToggleButton();
        lblHorarios = new javax.swing.JLabel();
        cbHorario = new javax.swing.JComboBox<>();
        panelContenedor = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlAsientosSel = new javax.swing.JList<>();
        lblAsientosSeleccionados = new javax.swing.JLabel();
        lblMetodoDePago = new javax.swing.JLabel();
        cbMetodoDePago = new javax.swing.JComboBox<>();
        lblTotalAPagar = new javax.swing.JLabel();
        btnConfirmarVenta = new javax.swing.JButton();
        jtfCodigoTicket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarTicket = new javax.swing.JButton();
        btnAnularTicket = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextPane1.setText("Su nombre");
        jScrollPane2.setViewportView(jTextPane1);

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtfDNI.setText("Ingrese su DNI");
        jtfDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDNIActionPerformed(evt);
            }
        });

        lblDNI.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        lblDNI.setText("DNI");

        lblGestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGestion.setText("Gestion de tickets");

        lblPelicula.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        lblPelicula.setText("Pelicula");

        cbPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSala.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        lblSala.setText("Sala");

        cbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSeleccionarAsientos.setText("Seleccionar asientos");
        btnSeleccionarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarAsientosActionPerformed(evt);
            }
        });

        lblHorarios.setText("Horario");

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jlAsientosSel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jlAsientosSel);

        lblAsientosSeleccionados.setText("Asientos seleccionados");

        lblMetodoDePago.setText("Metodo de pago");

        cbMetodoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Ticket:");

        btnBuscarTicket.setText("Buscar");
        btnBuscarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTicketActionPerformed(evt);
            }
        });

        btnAnularTicket.setText("Anular ticket");
        btnAnularTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularTicketActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAsientosSeleccionados)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblGestion)
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfCodigoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarTicket))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDNI)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscar)
                                    .addGap(29, 29, 29)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeleccionarAsientos)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblHorarios)
                                                .addGap(26, 26, 26)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbPelicula, 0, 131, Short.MAX_VALUE)
                                            .addComponent(cbHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(46, 46, 46)
                                        .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMetodoDePago)
                                .addGap(18, 18, 18)
                                .addComponent(cbMetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(lblTotalAPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmarVenta)
                                .addGap(64, 64, 64)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAnularTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblGestion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscarTicket))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorarios))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarAsientos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAsientosSeleccionados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodoDePago)
                    .addComponent(cbMetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalAPagar)
                    .addComponent(btnConfirmarVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnularTicket)
                    .addComponent(btnCancelar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDNIActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int dni = Integer.parseInt(jtfDNI.getText());
            CompradorData compData = new CompradorData();

            compradorActual = compData.buscarCompradorPorDni(dni);

            if (compradorActual != null) {

                jTextPane1.setText(compradorActual.getNombre());
                JOptionPane.showMessageDialog(this, "Comprador encontrado: " + compradorActual.getNombre());
            } else {

                jTextPane1.setText("Comprador no existe");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DNI debe ser un número válido.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSeleccionarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarAsientosActionPerformed
        ticketActual = null;
    
    Proyeccion proyeccionSeleccionada = (Proyeccion) ((javax.swing.JComboBox) cbHorario).getSelectedItem();

    if (proyeccionSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una función primero.");
        return;
    }

    final double precioUnitario = proyeccionSeleccionada.getPrecio();
    
    if (miPanelSalas == null) {
        miPanelSalas = new PanelElegirAsientos();
    }
    
    // 2. CONFIGURACIÓN DEL OBSERVADOR
    miPanelSalas.setObservador((listaSeleccionada) -> {

        DefaultListModel<String> modelo = new DefaultListModel<>();
        double total = 0;

        for (Asiento a : listaSeleccionada) {
            modelo.addElement("Fila " + a.getFila() + " - Nro " + a.getNumero());
            total += precioUnitario; 
        }

        jlAsientosSel.setModel(modelo);
        lblTotalAPagar.setText("$ " + String.format("%.2f", total));
    });

    // 3. CARGAR ASIENTOS: Pasamos una lista vacía para el modo 'Nueva Venta'
    AsientoData ad = new AsientoData();
    List<Asiento> asientosBD = ad.listarAsientosPorProyeccion(proyeccionSeleccionada.getCodProyeccion());

    miPanelSalas.cargarAsientos(asientosBD, new ArrayList<>()); // <<-- SEGUNDO PARÁMETRO VACÍO
    
    // 4. Mostrar panel
    panelContenedor.removeAll();
    panelContenedor.setLayout(new java.awt.BorderLayout());
    panelContenedor.add(miPanelSalas, java.awt.BorderLayout.CENTER);
    panelContenedor.revalidate();
    panelContenedor.repaint();
    }//GEN-LAST:event_btnSeleccionarAsientosActionPerformed
    private void filtrarCombos() {
        String tituloSeleccionado = (String) cbPelicula.getSelectedItem();
        String salaString = (String) cbSala.getSelectedItem();

        int nroSalaSeleccionada = 0;

        if (salaString != null && salaString.contains(":")) {
            try {
                nroSalaSeleccionada = Integer.parseInt(salaString.split(":")[1].trim());
            } catch (NumberFormatException ignored) {

            }
        }

        ProyeccionData proyData = new ProyeccionData();

        List<Proyeccion> proyecciones = proyData.listaProyecciones();

        cbHorario.removeAllItems();

        for (Proyeccion p : proyecciones) {

            boolean coincidePelicula = p.getTitulo().equals(tituloSeleccionado);
            boolean coincideSala = (nroSalaSeleccionada == 0) || (p.getNroSala() == nroSalaSeleccionada);

            if (coincidePelicula && coincideSala) {
                ((javax.swing.JComboBox) cbHorario).addItem(p);
            }
        }
    }

    private void cargarDatosIniciales() {

        PeliculaData pelData = new PeliculaData();
        List<Pelicula> peliculas = pelData.listarPeliculasEnCartelera();

        cbPelicula.removeAllItems();
        for (Pelicula p : peliculas) {
            cbPelicula.addItem(p.getTitulo());
        }

        SalaData salaData = new SalaData();
        List<Sala> salas = salaData.listarSalas();

        cbSala.removeAllItems();
        for (Sala s : salas) {
            cbSala.addItem("Sala Nro: " + s.getNroSala());
        }

        cbMetodoDePago.removeAllItems();
        cbMetodoDePago.addItem("Efectivo / Contado");
        cbMetodoDePago.addItem("Débito");
        cbMetodoDePago.addItem("Crédito");
        cbMetodoDePago.addItem("Mercado Pago");

        cbPelicula.addActionListener(e -> filtrarCombos());
        cbSala.addActionListener(e -> filtrarCombos());

        filtrarCombos();
    }

    private void filtrarProyecciones() {
        String tituloSeleccionado = (String) cbPelicula.getSelectedItem();
        if (tituloSeleccionado == null || tituloSeleccionado.isEmpty()) {
            return;
        }

        ProyeccionData proyData = new ProyeccionData();
        List<Proyeccion> todasProyecciones = proyData.listaProyecciones();

        cbHorario.removeAllItems();

        for (Proyeccion p : todasProyecciones) {
            if (p.getTitulo().equals(tituloSeleccionado)) {
                ((javax.swing.JComboBox) cbHorario).addItem(p);
            }
        }

    }

    private void limpiarVista() {
        compradorActual = null;
        ticketActual = null;

        jtfDNI.setText("");
        jTextPane1.setText("Buscador de Comprador");
        jtfCodigoTicket.setText("");
        lblTotalAPagar.setText("$0.00");

        cbPelicula.setSelectedIndex(-1);
        cbSala.setSelectedIndex(-1);
        cbHorario.setSelectedIndex(-1);

        jlAsientosSel.setModel(new DefaultListModel<>());

        miPanelSalas.cargarAsientos(new ArrayList<>(), new ArrayList<>());
    }
    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        if (compradorActual == null) {
            JOptionPane.showMessageDialog(this, "Debe buscar o registrar un Comprador (DNI).");
            return;
        }
        if (cbMetodoDePago.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un Método de Pago.");
            return;
        }

        List<Asiento> asientosComprados = miPanelSalas.getAsientosSeleccionados();
        if (asientosComprados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún asiento.");
            return;
        }

        Proyeccion proyeccion = (Proyeccion) cbHorario.getSelectedItem();

        List<DetalleTicket> detalles = new ArrayList<>();
        double montoTotal = 0;

        for (Asiento asiento : asientosComprados) {
            DetalleTicket detalle = new DetalleTicket();
            detalle.setAsiento(asiento);

            double subtotal = proyeccion.getPrecio();
            detalle.setSubtotal(subtotal);
            montoTotal += subtotal;
            detalles.add(detalle);
        }

        TicketCompra nuevoTicket = new TicketCompra();
        nuevoTicket.setComprador(compradorActual);
        nuevoTicket.setFechaCompra(new Date()); // java.util.Date
        nuevoTicket.setProyeccion(proyeccion);
        nuevoTicket.setMontoTotal(montoTotal);
        nuevoTicket.setDetalles(detalles);

        AsientoData asientoData = new AsientoData();
        for (Asiento asiento : asientosComprados) {
            asientoData.actualizarEstadoAsiento(asiento.getCodAsiento(), "OCUPADO");
        }

        TicketCompraData ticketData = new TicketCompraData();
        boolean exito = ticketData.guardarTicket(nuevoTicket);

        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Venta Exitosa! Ticket Nro: " + nuevoTicket.getCodTicket());
            limpiarVista();
        } else {
            JOptionPane.showMessageDialog(this, "Venta fallida. Consulte el error en la consola.");
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnBuscarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTicketActionPerformed
        try {
    
        int codTicket = Integer.parseInt(jtfCodigoTicket.getText().trim());

      
        TicketCompraData ticketData = new TicketCompraData();
        ticketActual = ticketData.buscarTicketPorId(codTicket); 

        if (ticketActual == null) {
            JOptionPane.showMessageDialog(this, "Ticket N° " + codTicket + " no encontrado o no existe.");
            limpiarVista(); 
            return;
        }

        
        Proyeccion proy = ticketActual.getProyeccion();
        
 
        compradorActual = ticketActual.getComprador();
        jtfDNI.setText(String.valueOf(compradorActual.getDni()));
        jTextPane1.setText(compradorActual.getNombre());
        
       
        cbPelicula.setSelectedItem(proy.getTitulo()); 
        cbSala.setSelectedItem("Sala Nro: " + proy.getNroSala()); 
        
      
        ((javax.swing.JComboBox)cbHorario).setSelectedItem(proy); 

   
        AsientoData asientoData = new AsientoData();
        List<Asiento> asientosCompletos = asientoData.listarAsientosPorProyeccion(proy.getCodProyeccion());
        
       
        List<Asiento> asientosVendidos = new ArrayList<>();
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        double totalTicket = 0;
        
        for(DetalleTicket dt : ticketActual.getDetalles()) {
            Asiento asientoTicket = dt.getAsiento();
            asientosVendidos.add(asientoTicket);
            modeloLista.addElement(asientoTicket.getFila() + "-" + asientoTicket.getNumero() + " ($" + String.format("%.2f", dt.getSubtotal()) + ")");
            totalTicket += dt.getSubtotal();
        }
        
    
        miPanelSalas.cargarAsientos(asientosCompletos, asientosVendidos); 
        
      
        jlAsientosSel.setModel(modeloLista);
        lblTotalAPagar.setText("$" + String.format("%.2f", totalTicket));
        
        panelContenedor.removeAll();
        panelContenedor.setLayout(new java.awt.BorderLayout());
        panelContenedor.add(miPanelSalas, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
        
        JOptionPane.showMessageDialog(this, "Ticket N° " + codTicket + " cargado. Puede proceder a la anulación.");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingrese un código de ticket numérico válido.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar el ticket: " + ex.getMessage());
        limpiarVista();
    }
    }//GEN-LAST:event_btnBuscarTicketActionPerformed

    private void btnAnularTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularTicketActionPerformed
        if (ticketActual == null) {
            JOptionPane.showMessageDialog(this, "Debe cargar un ticket primero para anularlo.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de anular el Ticket N° " + ticketActual.getCodTicket() + "? Esta acción es irreversible.",
                "Confirmar Anulación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {

            try {
                TicketCompraData ticketData = new TicketCompraData();
                AsientoData asientoData = new AsientoData();

                for (DetalleTicket dt : ticketActual.getDetalles()) {
                    asientoData.actualizarEstadoAsiento(dt.getAsiento().getCodAsiento(), "LIBRE");
                }

                ticketData.eliminarTicket(ticketActual.getCodTicket());

                JOptionPane.showMessageDialog(this, "Ticket N° " + ticketActual.getCodTicket() + " anulado y asientos liberados.");
                limpiarVista();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al anular: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAnularTicketActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarVista();
        JOptionPane.showMessageDialog(this, "Selección cancelada y vista limpia.");
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularTicket;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnBuscarTicket;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JToggleButton btnSeleccionarAsientos;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<String> cbMetodoDePago;
    private javax.swing.JComboBox<String> cbPelicula;
    private javax.swing.JComboBox<String> cbSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> jlAsientosSel;
    private javax.swing.JTextField jtfCodigoTicket;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JLabel lblAsientosSeleccionados;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblGestion;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblMetodoDePago;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
