/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elias
 */
public class PanelPeliculas extends javax.swing.JPanel {
    private PeliculaData peliculaData;
    private DefaultTableModel modeloTabla;
    private List<Pelicula> listaCompletaPeliculas;
    /**
     * Creates new form PanelPeliculas
     */
    public PanelPeliculas() {
        initComponents();
        peliculaData = new PeliculaData();
        modeloTabla = (DefaultTableModel) jtblPelicula.getModel();
        
        this.listaCompletaPeliculas = peliculaData.listarTodasLasPeliculas();
        llenarTabla(this.listaCompletaPeliculas);
    }
    
    private void llenarTabla(List<Pelicula> peliculas){
        modeloTabla.setRowCount(0);
        
        for (Pelicula p : peliculas) {
            String estado = p.isEnCartelera() ? "En Cartelera" : "Proximo Estreno";
            modeloTabla.addRow(new Object[]{
            p.getTitulo(),
            p.getDirector(),
            p.getOrigen(),
            p.getGenero(),
            estado
        });   

        };
        }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioFiltro = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        lblTituloPeli = new javax.swing.JLabel();
        rdbtnVerTodas = new javax.swing.JRadioButton();
        rdbtnVerCartelera = new javax.swing.JRadioButton();
        rdbtnVerEstrenos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPelicula = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnIrAAdmin = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(660, 664));

        lblTituloPeli.setText("PELICULAS");

        radioFiltro.add(rdbtnVerTodas);
        rdbtnVerTodas.setText("Ver Todas");
        rdbtnVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnVerTodasActionPerformed(evt);
            }
        });

        radioFiltro.add(rdbtnVerCartelera);
        rdbtnVerCartelera.setText("Ver En Cartelera");
        rdbtnVerCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnVerCarteleraActionPerformed(evt);
            }
        });

        radioFiltro.add(rdbtnVerEstrenos);
        rdbtnVerEstrenos.setText("Ver Estrenos");
        rdbtnVerEstrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnVerEstrenosActionPerformed(evt);
            }
        });

        jtblPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Director", "Genero", "Origen"
            }
        ));
        jScrollPane1.setViewportView(jtblPelicula);

        btnIrAAdmin.setText("Panel Admin");
        btnIrAAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbtnVerTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbtnVerCartelera)
                        .addGap(88, 88, 88)
                        .addComponent(rdbtnVerEstrenos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIrAAdmin))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblTituloPeli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrAAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnVerTodas)
                    .addComponent(rdbtnVerCartelera)
                    .addComponent(rdbtnVerEstrenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        rdbtnVerTodas.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnVerEstrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnVerEstrenosActionPerformed
        // TODO add your handling code here:
        List<Pelicula> peliculasFiltradas = new ArrayList<>();

    if (rdbtnVerCartelera.isSelected()) {
        
       
        peliculasFiltradas = peliculaData.listarPeliculasEnCartelera();

    } else if (rdbtnVerEstrenos.isSelected()) {
        
        
        peliculasFiltradas = peliculaData.listarPeliculasEstrenos();

    } else { 
        
        
        peliculasFiltradas = peliculaData.listarTodasLasPeliculas();
    }

    
    llenarTabla(peliculasFiltradas);
    }//GEN-LAST:event_rdbtnVerEstrenosActionPerformed

    private void btnIrAAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAAdminActionPerformed
        // TODO add your handling code here:
        PanelABCPeliculas panelAdmin = new PanelABCPeliculas();
        
        JDialog dialogoAdmin = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogoAdmin.setTitle("Administracion de Peliculas");
        dialogoAdmin.add(panelAdmin);
        dialogoAdmin.pack();
        
        dialogoAdmin.setLocationRelativeTo(null);
        dialogoAdmin.setVisible(true);
        
    }//GEN-LAST:event_btnIrAAdminActionPerformed

    private void rdbtnVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnVerTodasActionPerformed
        // TODO add your handling code here:
        List<Pelicula> peliculasFiltradas = new ArrayList<>();

    if (rdbtnVerCartelera.isSelected()) {
        
       
        peliculasFiltradas = peliculaData.listarPeliculasEnCartelera();

    } else if (rdbtnVerEstrenos.isSelected()) {
        
        
        peliculasFiltradas = peliculaData.listarPeliculasEstrenos();

    } else { 
        
        
        peliculasFiltradas = peliculaData.listarTodasLasPeliculas();
    }

    
    llenarTabla(peliculasFiltradas);
    }//GEN-LAST:event_rdbtnVerTodasActionPerformed

    private void rdbtnVerCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnVerCarteleraActionPerformed
        // TODO add your handling code here:
        List<Pelicula> peliculasFiltradas = new ArrayList<>();

    if (rdbtnVerCartelera.isSelected()) {
        
       
        peliculasFiltradas = peliculaData.listarPeliculasEnCartelera();

    } else if (rdbtnVerEstrenos.isSelected()) {
        
        
        peliculasFiltradas = peliculaData.listarPeliculasEstrenos();

    } else { 
        
        
        peliculasFiltradas = peliculaData.listarTodasLasPeliculas();
    }

    
    llenarTabla(peliculasFiltradas);
    }//GEN-LAST:event_rdbtnVerCarteleraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrAAdmin;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtblPelicula;
    private javax.swing.JLabel lblTituloPeli;
    private javax.swing.ButtonGroup radioFiltro;
    private javax.swing.JRadioButton rdbtnVerCartelera;
    private javax.swing.JRadioButton rdbtnVerEstrenos;
    private javax.swing.JRadioButton rdbtnVerTodas;
    // End of variables declaration//GEN-END:variables
}
