/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class PanelABCPeliculas extends javax.swing.JPanel {
 
    /**
     * Creates new form PanelABCMPeliculas
     */
    public PanelABCPeliculas() {
        initComponents();
    }
    private void limpiarCamposYResetFormulario() {
    
    jtfTitulo.setText("");
    jtfDirector.setText("");
    jtfOrigen.setText("");
    jtfGenero.setText("");

    
    jdcEstreno.setDate(null);

   
    jcbEnCartelera.setSelected(false);

    
    jtfDirector.setEditable(true);
    jtfTitulo.setEditable(true);

    
    btnGuardar.setEnabled(true);   
    btnModificar.setEnabled(false); 
    btnBorrar.setEnabled(false);    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jtfDirector = new javax.swing.JTextField();
        jtfOrigen = new javax.swing.JTextField();
        jtfGenero = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jdcEstreno = new com.toedter.calendar.JDateChooser();
        lblFechaEstreno = new javax.swing.JLabel();
        lblEnCartelra = new javax.swing.JLabel();
        jcbEnCartelera = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitle.setText("Panel Admin");

        lblTitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(java.awt.SystemColor.controlShadow);
        lblTitulo.setText("Titulo:");

        lblDirector.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblDirector.setForeground(java.awt.SystemColor.controlShadow);
        lblDirector.setText("Director:");

        lblOrigen.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblOrigen.setForeground(java.awt.SystemColor.controlShadow);
        lblOrigen.setText("Origen:");

        lblGenero.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblGenero.setForeground(java.awt.SystemColor.controlShadow);
        lblGenero.setText("Genero:");

        jtfTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTituloActionPerformed(evt);
            }
        });

        jtfOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOrigenActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblFechaEstreno.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblFechaEstreno.setForeground(java.awt.SystemColor.controlShadow);
        lblFechaEstreno.setText("Fecha Estr.:");

        lblEnCartelra.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblEnCartelra.setForeground(java.awt.SystemColor.controlShadow);
        lblEnCartelra.setText("En Cartelera:");

        jcbEnCartelera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbEnCartelera.setText("Si");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOrigen)
                                    .addComponent(lblGenero)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEnCartelra)
                                    .addComponent(lblFechaEstreno))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcbEnCartelera)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar))
                                    .addComponent(jtfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblTitle)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirector))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrigen)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaEstreno))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnCartelra)
                    .addComponent(jcbEnCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTituloActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = jtfTitulo.getText();
            String Director = jtfDirector.getText();
            String Origen = jtfOrigen.getText();
            String Genero = jtfGenero.getText();
            Date Estreno = jdcEstreno.getDate();
            Boolean enCartelera = jcbEnCartelera.isSelected();
            if (titulo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de Titulo no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Director.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de Director no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Origen.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de Origen no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Genero.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo de Genero no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Pelicula pelicula = new Pelicula(titulo, Director, Origen, Genero, Estreno, enCartelera);
            PeliculaData peliData = new PeliculaData();
            peliData.agregarPelicula(pelicula);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al guardar la Pelicula", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCamposYResetFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jtfOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOrigenActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
        String titulo = jtfTitulo.getText();
        String director = jtfDirector.getText();
        
        PeliculaData peliculaData = new PeliculaData();

        if (titulo.isEmpty() || director.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Titulo o Director estan vacios. Busque una pelicula primero.");
            return;
        }

        
        String origen = jtfOrigen.getText();
        String genero = jtfGenero.getText();
        
        
        java.util.Date estreno = jdcEstreno.getDate();
        
       
        boolean enCartelera = jcbEnCartelera.isSelected();

        
        Pelicula peliculaModificada = new Pelicula();
        peliculaModificada.setTitulo(titulo); 
        peliculaModificada.setDirector(director); 
        peliculaModificada.setOrigen(origen);
        peliculaModificada.setGenero(genero);
        peliculaModificada.setEstreno(estreno);
        peliculaModificada.setEnCartelera(enCartelera);

        
        peliculaData.modificarPelicula(peliculaModificada);

       

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al modificar la pelicula: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String titulo = jtfTitulo.getText();
        String director = jtfDirector.getText();
        PeliculaData peliculaData = new PeliculaData();

    
        if (titulo.isEmpty() || director.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Título y el Director para buscar.");
            return;
        }

        try {
        
            Pelicula peliculaEncontrada = peliculaData.buscarPelicula(titulo, director);

        
            if (peliculaEncontrada != null) {
            
            
            jtfOrigen.setText(peliculaEncontrada.getOrigen());
            jtfGenero.setText(peliculaEncontrada.getGenero());

            
            if (peliculaEncontrada.getEstreno() != null) {
               
               jdcEstreno.setDate(peliculaEncontrada.getEstreno());
            }

            
            jcbEnCartelera.setSelected(peliculaEncontrada.isEnCartelera());

            
            btnModificar.setEnabled(true);
            btnBorrar.setEnabled(true);
            btnGuardar.setEnabled(false); 
            
            
            jtfTitulo.setEditable(false);
            jtfDirector.setEditable(false);

        } else {
            
            JOptionPane.showMessageDialog(this, "Película no encontrada.");
            
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al buscar la película: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbEnCartelera;
    private com.toedter.calendar.JDateChooser jdcEstreno;
    private javax.swing.JTextField jtfDirector;
    private javax.swing.JTextField jtfGenero;
    private javax.swing.JTextField jtfOrigen;
    private javax.swing.JTextField jtfTitulo;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEnCartelra;
    private javax.swing.JLabel lblFechaEstreno;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
