/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Comprador;
import Persistencia.CompradorData;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class VistaComprador extends javax.swing.JPanel {
    
    private CompradorData compData;

    /**
     * Creates new form GestionCompradores
     */
    public VistaComprador() {
        initComponents();
        this.compData = new CompradorData();
    }
    
    private void limpiarCampos() {
    jtfDni.setText("");
    jtfNombre.setText("");
    jpfPass.setText("");
    jDateFechaNac.setDate(null);
    
    // Reiniciar botones
    btnActualizar.setEnabled(false);
    btnEliminar.setEnabled(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlPass = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jpfPass = new javax.swing.JPasswordField();
        jDateFechaNac = new com.toedter.calendar.JDateChooser();
        btnLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jlDni = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(670, 664));
        setMinimumSize(new java.awt.Dimension(200, 180));
        setPreferredSize(new java.awt.Dimension(670, 664));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jlNombre.setForeground(java.awt.SystemColor.controlShadow);
        jlNombre.setText("Nombre y Apellido:");
        add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 40));
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 175, -1));

        jlPass.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jlPass.setForeground(java.awt.SystemColor.controlShadow);
        jlPass.setText("Password:");
        add(jlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 60));

        jlFechaNac.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jlFechaNac.setForeground(java.awt.SystemColor.controlShadow);
        jlFechaNac.setText("Fecha Nacimiento:");
        add(jlFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 40));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 110, 50));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 110, 50));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 110, 50));

        jlTitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jlTitulo.setForeground(java.awt.SystemColor.controlShadow);
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Gestion compradores");
        add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 60));
        add(jpfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 175, -1));
        add(jDateFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 175, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 110, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 650, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, 650, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 650, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlDni.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jlDni.setForeground(new java.awt.Color(0, 153, 153));
        jlDni.setText("DNI:");

        jtfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jlDni, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jlDni, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 650, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
        int dni = Integer.parseInt(jtfDni.getText());
        Comprador comp = compData.buscarCompradorPorDni(dni);

        if (comp != null) {
            // Rellenar campos
            jtfNombre.setText(comp.getNombre());
            jpfPass.setText(comp.getPassword());
            jDateFechaNac.setDate(comp.getFechaNac()); // Directo, porque ambos son java.util.Date
            
            // Habilitar/deshabilitar botones
            btnActualizar.setEnabled(true);
            btnEliminar.setEnabled(true);
        } else {
            // Si no existe, limpiamos por si acaso
            limpiarCampos();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un DNI válido (solo números).");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
            try {
        int dni = Integer.parseInt(jtfDni.getText());
        String nombre = jtfNombre.getText();
        String pass = new String(jpfPass.getPassword()); // Obtener pass
        
        // Obtener fecha del JDateChooser
        java.util.Date fecha = jDateFechaNac.getDate();
        
        if (nombre.isEmpty() || pass.isEmpty() || fecha == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
        }

        Comprador nuevo = new Comprador(dni, nombre, fecha, pass, null); // El null es por la lista de tickets
        compData.guardarComprador(nuevo);
        
        limpiarCampos();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un DNI válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
        int dni = Integer.parseInt(jtfDni.getText()); // DNI no se modifica, es la clave
        String nombre = jtfNombre.getText();
        String pass = new String(jpfPass.getPassword());
        java.util.Date fecha = jDateFechaNac.getDate();
        
        if (nombre.isEmpty() || pass.isEmpty() || fecha == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
        }

        Comprador comp = new Comprador(dni, nombre, fecha, pass, null);
        compData.actualizarComprador(comp);
        
        limpiarCampos();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "DNI inválido.");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
        int dni = Integer.parseInt(jtfDni.getText());
        
        // Pedir confirmación
        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar este comprador?", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            compData.eliminarComprador(dni);
            limpiarCampos();
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "DNI inválido para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
                this.limpiarCampos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jtfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private com.toedter.calendar.JDateChooser jDateFechaNac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
